(autoload 'gitsum-undo                          "gitsum" "" t)
(autoload 'gitsum-refresh                       "gitsum" "" t)
(autoload 'gitsum-kill-dwim                     "gitsum" "" t)
(autoload 'gitsum-commit                        "gitsum" "" t)
(autoload 'gitsum-amend                         "gitsum" "" t)
(autoload 'gitsum-push                          "gitsum" "" t)
(autoload 'gitsum-revert                        "gitsum" "" t)
(autoload 'gitsum-do-commit                     "gitsum" "" t)
(autoload 'gitsum-kill-buffer                   "gitsum" "" t)
(autoload 'gitsum-switch-to-git-status          "gitsum" "" t)
(autoload 'gitsum-switch-from-git-status        "gitsum" "" t)
(autoload 'gitsum-find-buffer                   "gitsum" "" nil)
(autoload 'gitsum                               "gitsum" "" t)
(provide 'gitsum-mode-epackage-autoloads)
